# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

name: Master workflow
on:
  push:
    branches:
      - master
      - GHA-integration
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build
        run: |
          CGO_ENABLED=1 go build -o build/_output/onos-topo ./cmd/onos-topo
          go build -o build/_output/topo-generator ./cmd/topo-generator
          go build -o build/_output/topo-visualizer ./cmd/topo-visualizer

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit tests
        run: |
          go test -race github.com/onosproject/onos-topo/...

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build Docker image
        run: |
          git clone https://github.com/onosproject/build-tools.git build/build-tools
          go mod vendor
          docker build --platform linux/x86_64 . -f build/onos-topo/Dockerfile -t onosproject/onos-topo:latest
          rm -rf vendor

  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: reuse lint
        uses: fsfe/reuse-action@v2

  fossa-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: FOSSA scan
        uses: fossa-contrib/fossa-action@v3
        with:
          fossa-api-key: 9dc8fa92e3dd565687317beb87b56d89
